version: '3.3'

services:
  mongo:
    image: mongo:4.4
    environment:
      DOCKER_HOST: localhost
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123
    ports:
      - 27017:27017
  mongo-e2e:
    image: mongo:4.4
    environment:
      DOCKER_HOST: localhost
      MONGO_INITDB_ROOT_USERNAME: e2etest
      MONGO_INITDB_ROOT_PASSWORD: e2etestpass
    ports:
      - 27017:27017
